export default [
    {
      "atomicNumber": 1,
      "symbol": "H",
      "name": "Hidrojen",
      "atomicMass": "1.00794(4)",
      "electronicConfiguration": "1s1",
      "electronegativity": 2.2,
      "atomicRadius": 37,
      "ionRadius": "bilinmiyor",
      "vanDerWaalsRadius": 120,
      "ionizationEnergy": 1312,
      "electronAffinity": -73,
      "oxidationStates": "-1, 1",
      "standardState": "Gaz",
      "bondingType": "İki Atomlu",
      "meltingPoint": 14,
      "boilingPoint": 20,
      "density": 0.0000899,
      "groupBlock": "ametal",
      "yearDiscovered": 1766,
      "block": "s",
      "period": 1,
      "group": 1
    },
    {
      "atomicNumber": 2,
      "symbol": "He",
      "name": "Helyum",
      "atomicMass": "4.002602(2)",
      "electronicConfiguration": "1s2",
      "electronegativity": "bilinmiyor",
      "atomicRadius": 32,
      "ionRadius": "bilinmiyor",
      "vanDerWaalsRadius": 140,
      "ionizationEnergy": 2372,
      "electronAffinity": 0,
      "oxidationStates": "bilinmiyor",
      "standardState": "Gaz",
      "bondingType": "atomik",
      "meltingPoint": "bilinmiyor",
      "boilingPoint": 4,
      "density": 0.0001785,
      "groupBlock": "soy gaz",
      "yearDiscovered": 1868,
      "block": "p",
      "period": 1,
      "group": 18
    },
    {
      "atomicNumber": 3,
      "symbol": "Li",
      "name": "Lityum",
      "atomicMass": "6.941(2)",
      "electronicConfiguration": "[He] 2s1",
      "electronegativity": 0.98,
      "atomicRadius": 134,
      "ionRadius": "76 (+1)",
      "vanDerWaalsRadius": 182,
      "ionizationEnergy": 520,
      "electronAffinity": -60,
      "oxidationStates": 1,
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 454,
      "boilingPoint": 1615,
      "density": 0.535,
      "groupBlock": "alkali metal",
      "yearDiscovered": 1817,
      "block": "s",
      "period": 2,
      "group": 1
    },
    {
      "atomicNumber": 4,
      "symbol": "Be",
      "name": "Berilyum",
      "atomicMass": "9.012182(3)",
      "electronicConfiguration": "[He] 2s2",
      "electronegativity": 1.57,
      "atomicRadius": 90,
      "ionRadius": "45 (+2)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 900,
      "electronAffinity": 0,
      "oxidationStates": 2,
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1560,
      "boilingPoint": 2743,
      "density": 1.848,
      "groupBlock": "alkali toprak metal",
      "yearDiscovered": 1798,
      "block": "s",
      "period": 2,
      "group": 2
    },
    {
      "atomicNumber": 5,
      "symbol": "B",
      "name": "Bor",
      "atomicMass": "10.811(7)",
      "electronicConfiguration": "[He] 2s2 2p1",
      "electronegativity": 2.04,
      "atomicRadius": 82,
      "ionRadius": "27 (+3)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 801,
      "electronAffinity": -27,
      "oxidationStates": "1, 2, 3",
      "standardState": "Katı",
      "bondingType": "Kovalent Bağ",
      "meltingPoint": 2348,
      "boilingPoint": 4273,
      "density": 2.46,
      "groupBlock": "yarı metal",
      "yearDiscovered": 1807,
      "block": "p",
      "period": 2,
      "group": 13
    },
    {
      "atomicNumber": 6,
      "symbol": "C",
      "name": "Karbon",
      "atomicMass": "12.0107(8)",
      "electronicConfiguration": "[He] 2s2 2p2",
      "electronegativity": 2.55,
      "atomicRadius": 77,
      "ionRadius": "16 (+4)",
      "vanDerWaalsRadius": 170,
      "ionizationEnergy": 1087,
      "electronAffinity": -154,
      "oxidationStates": "-4, -3, -2, -1, 1, 2, 3, 4",
      "standardState": "Katı",
      "bondingType": "Kovalent Bağ",
      "meltingPoint": 3823,
      "boilingPoint": 4300,
      "density": 2.26,
      "groupBlock": "ametal",
      "yearDiscovered": "Antik",
      "block": "p",
      "period": 2,
      "group": 14
    },
    {
      "atomicNumber": 7,
      "symbol": "N",
      "name": "Azot",
      "atomicMass": "14.0067(2)",
      "electronicConfiguration": "[He] 2s2 2p3",
      "electronegativity": 3.04,
      "atomicRadius": 75,
      "ionRadius": "146 (-3)",
      "vanDerWaalsRadius": 155,
      "ionizationEnergy": 1402,
      "electronAffinity": -7,
      "oxidationStates": "-3, -2, -1, 1, 2, 3, 4, 5",
      "standardState": "Gaz",
      "bondingType": "İki Atomlu",
      "meltingPoint": 63,
      "boilingPoint": 77,
      "density": 0.001251,
      "groupBlock": "ametal",
      "yearDiscovered": 1772,
      "block": "p",
      "period": 2,
      "group": 15
    },
    {
      "atomicNumber": 8,
      "symbol": "O",
      "name": "Oksijen",
      "atomicMass": "15.9994(3)",
      "electronicConfiguration": "[He] 2s2 2p4",
      "electronegativity": 3.44,
      "atomicRadius": 73,
      "ionRadius": "140 (-2)",
      "vanDerWaalsRadius": 152,
      "ionizationEnergy": 1314,
      "electronAffinity": -141,
      "oxidationStates": "-2, -1, 1, 2",
      "standardState": "Gaz",
      "bondingType": "İki Atomlu",
      "meltingPoint": 55,
      "boilingPoint": 90,
      "density": 0.001429,
      "groupBlock": "ametal",
      "yearDiscovered": 1774,
      "block": "p",
      "period": 2,
      "group": 16
    },
    {
      "atomicNumber": 9,
      "symbol": "F",
      "name": "Flor",
      "atomicMass": "18.9984032(5)",
      "electronicConfiguration": "[He] 2s2 2p5",
      "electronegativity": 3.98,
      "atomicRadius": 71,
      "ionRadius": "133 (-1)",
      "vanDerWaalsRadius": 147,
      "ionizationEnergy": 1681,
      "electronAffinity": -328,
      "oxidationStates": -1,
      "standardState": "Gaz",
      "bondingType": "atomik",
      "meltingPoint": 54,
      "boilingPoint": 85,
      "density": 0.001696,
      "groupBlock": "halojen",
      "yearDiscovered": 1670,
      "block": "p",
      "period": 2,
      "group": 17
    },
    {
      "atomicNumber": 10,
      "symbol": "Ne",
      "name": "Neon",
      "atomicMass": "20.1797(6)",
      "electronicConfiguration": "[He] 2s2 2p6",
      "electronegativity": "bilinmiyor",
      "atomicRadius": 69,
      "ionRadius": "bilinmiyor",
      "vanDerWaalsRadius": 154,
      "ionizationEnergy": 2081,
      "electronAffinity": 0,
      "oxidationStates": "bilinmiyor",
      "standardState": "Gaz",
      "bondingType": "atomik",
      "meltingPoint": 25,
      "boilingPoint": 27,
      "density": 0.0009,
      "groupBlock": "soy gaz",
      "yearDiscovered": 1898,
      "block": "p",
      "period": 2,
      "group": 18
    },
    {
      "atomicNumber": 11,
      "symbol": "Na",
      "name": "Sodyum",
      "atomicMass": "22.98976928(2)",
      "electronicConfiguration": "[Ne] 3s1",
      "electronegativity": 0.93,
      "atomicRadius": 154,
      "ionRadius": "102 (+1)",
      "vanDerWaalsRadius": 227,
      "ionizationEnergy": 496,
      "electronAffinity": -53,
      "oxidationStates": "-1, 1",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 371,
      "boilingPoint": 1156,
      "density": 0.968,
      "groupBlock": "alkali metal",
      "yearDiscovered": 1807,
      "block": "s",
      "period": 3,
      "group": 1
    },
    {
      "atomicNumber": 12,
      "symbol": "Mg",
      "name": "Magnezyum",
      "atomicMass": "24.3050(6)",
      "electronicConfiguration": "[Ne] 3s2",
      "electronegativity": 1.31,
      "atomicRadius": 130,
      "ionRadius": "72 (+2)",
      "vanDerWaalsRadius": 173,
      "ionizationEnergy": 738,
      "electronAffinity": 0,
      "oxidationStates": "1, 2",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 923,
      "boilingPoint": 1363,
      "density": 1.738,
      "groupBlock": "alkali toprak metal",
      "yearDiscovered": 1808,
      "block": "s",
      "period": 3,
      "group": 2
    },
    {
      "atomicNumber": 13,
      "symbol": "Al",
      "name": "Alüminyum",
      "atomicMass": "26.9815386(8)",
      "electronicConfiguration": "[Ne] 3s2 3p1",
      "electronegativity": 1.61,
      "atomicRadius": 118,
      "ionRadius": "53.5 (+3)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 578,
      "electronAffinity": -43,
      "oxidationStates": "1, 3",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 933,
      "boilingPoint": 2792,
      "density": 2.7,
      "groupBlock": "metal",
      "yearDiscovered": "Antik",
      "block": "p",
      "period": 3,
      "group": 13
    },
    {
      "atomicNumber": 14,
      "symbol": "Si",
      "name": "Silisyum",
      "atomicMass": "28.0855(3)",
      "electronicConfiguration": "[Ne] 3s2 3p2",
      "electronegativity": 1.9,
      "atomicRadius": 111,
      "ionRadius": "40 (+4)",
      "vanDerWaalsRadius": 210,
      "ionizationEnergy": 787,
      "electronAffinity": -134,
      "oxidationStates": "-4, -3, -2, -1, 1, 2, 3, 4",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1687,
      "boilingPoint": 3173,
      "density": 2.33,
      "groupBlock": "yarı metal",
      "yearDiscovered": 1854,
      "block": "p",
      "period": 3,
      "group": 14
    },
    {
      "atomicNumber": 15,
      "symbol": "P",
      "name": "Fosfor",
      "atomicMass": "30.973762(2)",
      "electronicConfiguration": "[Ne] 3s2 3p3",
      "electronegativity": 2.19,
      "atomicRadius": 106,
      "ionRadius": "44 (+3)",
      "vanDerWaalsRadius": 180,
      "ionizationEnergy": 1012,
      "electronAffinity": -72,
      "oxidationStates": "-3, -2, -1, 1, 2, 3, 4, 5",
      "standardState": "Katı",
      "bondingType": "Kovalent Bağ",
      "meltingPoint": 317,
      "boilingPoint": 554,
      "density": 1.823,
      "groupBlock": "ametal",
      "yearDiscovered": 1669,
      "block": "p",
      "period": 3,
      "group": 15
    },
    {
      "atomicNumber": 16,
      "symbol": "S",
      "name": "Kükürt",
      "atomicMass": "32.065(5)",
      "electronicConfiguration": "[Ne] 3s2 3p4",
      "electronegativity": 2.58,
      "atomicRadius": 102,
      "ionRadius": "184 (-2)",
      "vanDerWaalsRadius": 180,
      "ionizationEnergy": 1000,
      "electronAffinity": -200,
      "oxidationStates": "-2, -1, 1, 2, 3, 4, 5, 6",
      "standardState": "Katı",
      "bondingType": "Kovalent Bağ",
      "meltingPoint": 388,
      "boilingPoint": 718,
      "density": 1.96,
      "groupBlock": "ametal",
      "yearDiscovered": "Antik",
      "block": "p",
      "period": 3,
      "group": 16
    },
    {
      "atomicNumber": 17,
      "symbol": "Cl",
      "name": "Klor",
      "atomicMass": "35.453(2)",
      "electronicConfiguration": "[Ne] 3s2 3p5",
      "electronegativity": 3.16,
      "atomicRadius": 99,
      "ionRadius": "181 (-1)",
      "vanDerWaalsRadius": 175,
      "ionizationEnergy": 1251,
      "electronAffinity": -349,
      "oxidationStates": "-1, 1, 2, 3, 4, 5, 6, 7",
      "standardState": "Gaz",
      "bondingType": "Kovalent Bağ",
      "meltingPoint": 172,
      "boilingPoint": 239,
      "density": 0.003214,
      "groupBlock": "halojen",
      "yearDiscovered": 1774,
      "block": "p",
      "period": 3,
      "group": 17
    },
    {
      "atomicNumber": 18,
      "symbol": "Ar",
      "name": "Argon",
      "atomicMass": "39.948(1)",
      "electronicConfiguration": "[Ne] 3s2 3p6",
      "electronegativity": "bilinmiyor",
      "atomicRadius": 97,
      "ionRadius": "bilinmiyor",
      "vanDerWaalsRadius": 188,
      "ionizationEnergy": 1521,
      "electronAffinity": 0,
      "oxidationStates": "bilinmiyor",
      "standardState": "Gaz",
      "bondingType": "atomik",
      "meltingPoint": 84,
      "boilingPoint": 87,
      "density": 0.001784,
      "groupBlock": "soy gaz",
      "yearDiscovered": 1894,
      "block": "p",
      "period": 3,
      "group": 18
    },
    {
      "atomicNumber": 19,
      "symbol": "K",
      "name": "Potasyum",
      "atomicMass": "39.0983(1)",
      "electronicConfiguration": "[Ar] 4s1",
      "electronegativity": 0.82,
      "atomicRadius": 196,
      "ionRadius": "138 (+1)",
      "vanDerWaalsRadius": 275,
      "ionizationEnergy": 419,
      "electronAffinity": -48,
      "oxidationStates": 1,
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 337,
      "boilingPoint": 1032,
      "density": 0.856,
      "groupBlock": "alkali metal",
      "yearDiscovered": 1807,
      "block": "s",
      "period": 4,
      "group": 1
    },
    {
      "atomicNumber": 20,
      "symbol": "Ca",
      "name": "Kalsiyum",
      "atomicMass": "40.078(4)",
      "electronicConfiguration": "[Ar] 4s2",
      "electronegativity": 1,
      "atomicRadius": 174,
      "ionRadius": "100 (+2)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 590,
      "electronAffinity": -2,
      "oxidationStates": 2,
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1115,
      "boilingPoint": 1757,
      "density": 1.55,
      "groupBlock": "alkali toprak metal",
      "yearDiscovered": "Antik",
      "block": "s",
      "period": 4,
      "group": 2
    },
    {
      "atomicNumber": 21,
      "symbol": "Sc",
      "name": "Skandiyum",
      "atomicMass": "44.955912(6)",
      "electronicConfiguration": "[Ar] 3d1 4s2",
      "electronegativity": 1.36,
      "atomicRadius": 144,
      "ionRadius": "74.5 (+3)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 633,
      "electronAffinity": -18,
      "oxidationStates": "1, 2, 3",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1814,
      "boilingPoint": 3103,
      "density": 2.985,
      "groupBlock": "geçiş metali",
      "yearDiscovered": 1876,
      "block": "d",
      "period": 4,
      "group": 3
    },
    {
      "atomicNumber": 22,
      "symbol": "Ti",
      "name": "Titanyum",
      "atomicMass": "47.867(1)",
      "electronicConfiguration": "[Ar] 3d2 4s2",
      "electronegativity": 1.54,
      "atomicRadius": 136,
      "ionRadius": "86 (+2)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 659,
      "electronAffinity": -8,
      "oxidationStates": "-1, 2, 3, 4",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1941,
      "boilingPoint": 3560,
      "density": 4.507,
      "groupBlock": "geçiş metali",
      "yearDiscovered": 1791,
      "block": "d",
      "period": 4,
      "group": 4
    },
    {
      "atomicNumber": 23,
      "symbol": "V",
      "name": "Vanadyum",
      "atomicMass": "50.9415(1)",
      "electronicConfiguration": "[Ar] 3d3 4s2",
      "electronegativity": 1.63,
      "atomicRadius": 125,
      "ionRadius": "79 (+2)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 651,
      "electronAffinity": -51,
      "oxidationStates": "-1, 2, 3, 4",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 2183,
      "boilingPoint": 3680,
      "density": 6.11,
      "groupBlock": "geçiş metali",
      "yearDiscovered": 1803,
      "block": "d",
      "period": 4,
      "group": 5
    },
    {
      "atomicNumber": 24,
      "symbol": "Cr",
      "name": "Krom",
      "atomicMass": "51.9961(6)",
      "electronicConfiguration": "[Ar] 3d5 4s1",
      "electronegativity": 1.66,
      "atomicRadius": 127,
      "ionRadius": "80 (+2*)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 653,
      "electronAffinity": -64,
      "oxidationStates": "-2, -1, 1, 2, 3, 4, 5, 6",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 2180,
      "boilingPoint": 2944,
      "density": 7.14,
      "groupBlock": "geçiş metali",
      "yearDiscovered": "Antik",
      "block": "d",
      "period": 4,
      "group": 6
    },
    {
      "atomicNumber": 25,
      "symbol": "Mn",
      "name": "Manganez",
      "atomicMass": "54.938045(5)",
      "electronicConfiguration": "[Ar] 3d5 4s2",
      "electronegativity": 1.55,
      "atomicRadius": 139,
      "ionRadius": "67 (+2)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 717,
      "electronAffinity": 0,
      "oxidationStates": "-3, -2, -1, 1, 2, 3, 4, 5, 6, 7",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1519,
      "boilingPoint": 2334,
      "density": 7.47,
      "groupBlock": "geçiş metali",
      "yearDiscovered": 1774,
      "block": "d",
      "period": 4,
      "group": 7
    },
    {
      "atomicNumber": 26,
      "symbol": "Fe",
      "name": "Demir",
      "atomicMass": "55.845(2)",
      "electronicConfiguration": "[Ar] 3d6 4s2",
      "electronegativity": 1.83,
      "atomicRadius": 125,
      "ionRadius": "78 (+2*)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 763,
      "electronAffinity": -16,
      "oxidationStates": "-2, -1, 1, 2, 3, 4, 5, 6",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1811,
      "boilingPoint": 3134,
      "density": 7.874,
      "groupBlock": "geçiş metali",
      "yearDiscovered": "Antik",
      "block": "d",
      "period": 4,
      "group": 8
    },
    {
      "atomicNumber": 27,
      "symbol": "Co",
      "name": "Kobalt",
      "atomicMass": "58.933195(5)",
      "electronicConfiguration": "[Ar] 3d7 4s2",
      "electronegativity": 1.88,
      "atomicRadius": 126,
      "ionRadius": "74.5 (+2*)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 760,
      "electronAffinity": -64,
      "oxidationStates": "-1, 1, 2, 3, 4, 5",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1768,
      "boilingPoint": 3200,
      "density": 8.9,
      "groupBlock": "geçiş metali",
      "yearDiscovered": "Antik",
      "block": "d",
      "period": 4,
      "group": 9
    },
    {
      "atomicNumber": 28,
      "symbol": "Ni",
      "name": "Nikel",
      "atomicMass": "58.6934(4)",
      "electronicConfiguration": "[Ar] 3d8 4s2",
      "electronegativity": 1.91,
      "atomicRadius": 121,
      "ionRadius": "69 (+2)",
      "vanDerWaalsRadius": 163,
      "ionizationEnergy": 737,
      "electronAffinity": -112,
      "oxidationStates": "-1, 1, 2, 3, 4",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1728,
      "boilingPoint": 3186,
      "density": 8.908,
      "groupBlock": "geçiş metali",
      "yearDiscovered": 1751,
      "block": "d",
      "period": 4,
      "group": 10
    },
    {
      "atomicNumber": 29,
      "symbol": "Cu",
      "name": "Bakır",
      "atomicMass": "63.546(3)",
      "electronicConfiguration": "[Ar] 3d10 4s1",
      "electronegativity": 1.9,
      "atomicRadius": 138,
      "ionRadius": "77 (+1)",
      "vanDerWaalsRadius": 140,
      "ionizationEnergy": 746,
      "electronAffinity": -118,
      "oxidationStates": "1, 2, 3, 4",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1358,
      "boilingPoint": 3200,
      "density": 8.92,
      "groupBlock": "geçiş metali",
      "yearDiscovered": "Antik",
      "block": "d",
      "period": 4,
      "group": 11
    },
    {
      "atomicNumber": 30,
      "symbol": "Zn",
      "name": "Çinko",
      "atomicMass": "65.38(2)",
      "electronicConfiguration": "[Ar] 3d10 4s2",
      "electronegativity": 1.65,
      "atomicRadius": 131,
      "ionRadius": "74 (+2)",
      "vanDerWaalsRadius": 139,
      "ionizationEnergy": 906,
      "electronAffinity": 0,
      "oxidationStates": 2,
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 693,
      "boilingPoint": 1180,
      "density": 7.14,
      "groupBlock": "geçiş metali",
      "yearDiscovered": 1746,
      "block": "d",
      "period": 4,
      "group": 12
    },
    {
      "atomicNumber": 31,
      "symbol": "Ga",
      "name": "Galyum",
      "atomicMass": "69.723(1)",
      "electronicConfiguration": "[Ar] 3d10 4s2 4p1",
      "electronegativity": 1.81,
      "atomicRadius": 126,
      "ionRadius": "62 (+3)",
      "vanDerWaalsRadius": 187,
      "ionizationEnergy": 579,
      "electronAffinity": -29,
      "oxidationStates": "1, 2, 3",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 303,
      "boilingPoint": 2477,
      "density": 5.904,
      "groupBlock": "metal",
      "yearDiscovered": 1875,
      "block": "p",
      "period": 4,
      "group": 13
    },
    {
      "atomicNumber": 32,
      "symbol": "Ge",
      "name": "Germanyum",
      "atomicMass": "72.64(1)",
      "electronicConfiguration": "[Ar] 3d10 4s2 4p2",
      "electronegativity": 2.01,
      "atomicRadius": 122,
      "ionRadius": "73 (+2)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 762,
      "electronAffinity": -119,
      "oxidationStates": "-4, 1, 2, 3, 4",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1211,
      "boilingPoint": 3093,
      "density": 5.323,
      "groupBlock": "yarı metal",
      "yearDiscovered": 1886,
      "block": "p",
      "period": 4,
      "group": 14
    },
    {
      "atomicNumber": 33,
      "symbol": "As",
      "name": "Arsenik",
      "atomicMass": "74.92160(2)",
      "electronicConfiguration": "[Ar] 3d10 4s2 4p3",
      "electronegativity": 2.18,
      "atomicRadius": 119,
      "ionRadius": "58 (+3)",
      "vanDerWaalsRadius": 185,
      "ionizationEnergy": 947,
      "electronAffinity": -78,
      "oxidationStates": "-3, 2, 3, 5",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1090,
      "boilingPoint": 887,
      "density": 5.727,
      "groupBlock": "yarı metal",
      "yearDiscovered": "Antik",
      "block": "p",
      "period": 4,
      "group": 15
    },
    {
      "atomicNumber": 34,
      "symbol": "Se",
      "name": "Selenyum",
      "atomicMass": "78.96(3)",
      "electronicConfiguration": "[Ar] 3d10 4s2 4p4",
      "electronegativity": 2.55,
      "atomicRadius": 116,
      "ionRadius": "198 (-2)",
      "vanDerWaalsRadius": 190,
      "ionizationEnergy": 941,
      "electronAffinity": -195,
      "oxidationStates": "-2, 2, 4, 6",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 494,
      "boilingPoint": 958,
      "density": 4.819,
      "groupBlock": "ametal",
      "yearDiscovered": 1817,
      "block": "p",
      "period": 4,
      "group": 16
    },
    {
      "atomicNumber": 35,
      "symbol": "Br",
      "name": "Brom",
      "atomicMass": "79.904(1)",
      "electronicConfiguration": "[Ar] 3d10 4s2 4p5",
      "electronegativity": 2.96,
      "atomicRadius": 114,
      "ionRadius": "196 (-1)",
      "vanDerWaalsRadius": 185,
      "ionizationEnergy": 1140,
      "electronAffinity": -325,
      "oxidationStates": "-1, 1, 3, 4, 5, 7",
      "standardState": "sıvı",
      "bondingType": "Kovalent Bağ",
      "meltingPoint": 266,
      "boilingPoint": 332,
      "density": 3.12,
      "groupBlock": "halojen",
      "yearDiscovered": 1826,
      "block": "p",
      "period": 4,
      "group": 17
    },
    {
      "atomicNumber": 36,
      "symbol": "Kr",
      "name": "Kripton",
      "atomicMass": "83.798(2)",
      "electronicConfiguration": "[Ar] 3d10 4s2 4p6",
      "electronegativity": "bilinmiyor",
      "atomicRadius": 110,
      "ionRadius": "bilinmiyor",
      "vanDerWaalsRadius": 202,
      "ionizationEnergy": 1351,
      "electronAffinity": 0,
      "oxidationStates": 2,
      "standardState": "Gaz",
      "bondingType": "atomik",
      "meltingPoint": 116,
      "boilingPoint": 120,
      "density": 0.00375,
      "groupBlock": "soy gaz",
      "yearDiscovered": 1898,
      "block": "p",
      "period": 4,
      "group": 18
    },
    {
      "atomicNumber": 37,
      "symbol": "Rb",
      "name": "Rubidyum",
      "atomicMass": "85.4678(3)",
      "electronicConfiguration": "[Kr] 5s1",
      "electronegativity": 0.82,
      "atomicRadius": 211,
      "ionRadius": "152 (+1)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 403,
      "electronAffinity": -47,
      "oxidationStates": 1,
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 312,
      "boilingPoint": 961,
      "density": 1.532,
      "groupBlock": "alkali metal",
      "yearDiscovered": 1861,
      "block": "s",
      "period": 5,
      "group": 1
    },
    {
      "atomicNumber": 38,
      "symbol": "Sr",
      "name": "Stronsiyum",
      "atomicMass": "87.62(1)",
      "electronicConfiguration": "[Kr] 5s2",
      "electronegativity": 0.95,
      "atomicRadius": 192,
      "ionRadius": "118 (+2)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 550,
      "electronAffinity": -5,
      "oxidationStates": 2,
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1050,
      "boilingPoint": 1655,
      "density": 2.63,
      "groupBlock": "alkali toprak metal",
      "yearDiscovered": 1790,
      "block": "s",
      "period": 5,
      "group": 2
    },
    {
      "atomicNumber": 39,
      "symbol": "Y",
      "name": "itriyum",
      "atomicMass": "88.90585(2)",
      "electronicConfiguration": "[Kr] 4d1 5s2",
      "electronegativity": 1.22,
      "atomicRadius": 162,
      "ionRadius": "90 (+3)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 600,
      "electronAffinity": -30,
      "oxidationStates": "1, 2, 3",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1799,
      "boilingPoint": 3618,
      "density": 4.472,
      "groupBlock": "geçiş metali",
      "yearDiscovered": 1794,
      "block": "d",
      "period": 5,
      "group": 3
    },
    {
      "atomicNumber": 40,
      "symbol": "Zr",
      "name": "Zirkonyum",
      "atomicMass": "91.224(2)",
      "electronicConfiguration": "[Kr] 4d2 5s2",
      "electronegativity": 1.33,
      "atomicRadius": 148,
      "ionRadius": "72 (+4)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 640,
      "electronAffinity": -41,
      "oxidationStates": "1, 2, 3, 4",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 2128,
      "boilingPoint": 4682,
      "density": 6.511,
      "groupBlock": "geçiş metali",
      "yearDiscovered": 1789,
      "block": "d",
      "period": 5,
      "group": 4
    },
    {
      "atomicNumber": 41,
      "symbol": "Nb",
      "name": "Niyobyum",
      "atomicMass": "92.90638(2)",
      "electronicConfiguration": "[Kr] 4d4 5s1",
      "electronegativity": 1.6,
      "atomicRadius": 137,
      "ionRadius": "72 (+3)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 652,
      "electronAffinity": -86,
      "oxidationStates": "-1, 2, 3, 4, 5",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 2750,
      "boilingPoint": 5017,
      "density": 8.57,
      "groupBlock": "geçiş metali",
      "yearDiscovered": 1801,
      "block": "d",
      "period": 5,
      "group": 5
    },
    {
      "atomicNumber": 42,
      "symbol": "Mo",
      "name": "Molibden",
      "atomicMass": "95.96(2)",
      "electronicConfiguration": "[Kr] 4d5 5s1",
      "electronegativity": 2.16,
      "atomicRadius": 145,
      "ionRadius": "69 (+3)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 684,
      "electronAffinity": -72,
      "oxidationStates": "-2, -1, 1, 2, 3, 4, 5, 6",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 2896,
      "boilingPoint": 4912,
      "density": 10.28,
      "groupBlock": "geçiş metali",
      "yearDiscovered": 1778,
      "block": "d",
      "period": 5,
      "group": 6
    },
    {
      "atomicNumber": 43,
      "symbol": "Tc",
      "name": "Teknesyum",
      "atomicMass": [
        98
      ],
      "electronicConfiguration": "[Kr] 4d5 5s2",
      "electronegativity": 1.9,
      "atomicRadius": 156,
      "ionRadius": "64.5 (+4)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 702,
      "electronAffinity": -53,
      "oxidationStates": "-3, -1, 1, 2, 3, 4, 5, 6, 7",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 2430,
      "boilingPoint": 4538,
      "density": 11.5,
      "groupBlock": "geçiş metali",
      "yearDiscovered": 1937,
      "block": "d",
      "period": 5,
      "group": 7
    },
    {
      "atomicNumber": 44,
      "symbol": "Ru",
      "name": "Rutenyum",
      "atomicMass": "101.07(2)",
      "electronicConfiguration": "[Kr] 4d7 5s1",
      "electronegativity": 2.2,
      "atomicRadius": 126,
      "ionRadius": "68 (+3)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 710,
      "electronAffinity": -101,
      "oxidationStates": "-2, 1, 2, 3, 4, 5, 6, 7, 8",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 2607,
      "boilingPoint": 4423,
      "density": 12.37,
      "groupBlock": "geçiş metali",
      "yearDiscovered": 1827,
      "block": "d",
      "period": 5,
      "group": 8
    },
    {
      "atomicNumber": 45,
      "symbol": "Rh",
      "name": "Rodyum",
      "atomicMass": "102.90550(2)",
      "electronicConfiguration": "[Kr] 4d8 5s1",
      "electronegativity": 2.28,
      "atomicRadius": 135,
      "ionRadius": "66.5 (+3)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 720,
      "electronAffinity": -110,
      "oxidationStates": "-1, 1, 2, 3, 4, 5, 6",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 2237,
      "boilingPoint": 3968,
      "density": 12.45,
      "groupBlock": "geçiş metali",
      "yearDiscovered": 1803,
      "block": "d",
      "period": 5,
      "group": 9
    },
    {
      "atomicNumber": 46,
      "symbol": "Pd",
      "name": "Paladyum",
      "atomicMass": "106.42(1)",
      "electronicConfiguration": "[Kr] 4d10",
      "electronegativity": 2.2,
      "atomicRadius": 131,
      "ionRadius": "59 (+1)",
      "vanDerWaalsRadius": 163,
      "ionizationEnergy": 804,
      "electronAffinity": -54,
      "oxidationStates": "2, 4",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1828,
      "boilingPoint": 3236,
      "density": 12.023,
      "groupBlock": "geçiş metali",
      "yearDiscovered": 1803,
      "block": "d",
      "period": 5,
      "group": 10
    },
    {
      "atomicNumber": 47,
      "symbol": "Ag",
      "name": "Gümüş",
      "atomicMass": "107.8682(2)",
      "electronicConfiguration": "[Kr] 4d10 5s1",
      "electronegativity": 1.93,
      "atomicRadius": 153,
      "ionRadius": "115 (+1)",
      "vanDerWaalsRadius": 172,
      "ionizationEnergy": 731,
      "electronAffinity": -126,
      "oxidationStates": "1, 2, 3",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1235,
      "boilingPoint": 2435,
      "density": 10.49,
      "groupBlock": "geçiş metali",
      "yearDiscovered": "Antik",
      "block": "d",
      "period": 5,
      "group": 11
    },
    {
      "atomicNumber": 48,
      "symbol": "Cd",
      "name": "Kadmiyum",
      "atomicMass": "112.411(8)",
      "electronicConfiguration": "[Kr] 4d10 5s2",
      "electronegativity": 1.69,
      "atomicRadius": 148,
      "ionRadius": "95 (+2)",
      "vanDerWaalsRadius": 158,
      "ionizationEnergy": 868,
      "electronAffinity": 0,
      "oxidationStates": 2,
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 594,
      "boilingPoint": 1040,
      "density": 8.65,
      "groupBlock": "geçiş metali",
      "yearDiscovered": 1817,
      "block": "d",
      "period": 5,
      "group": 12
    },
    {
      "atomicNumber": 49,
      "symbol": "In",
      "name": "İndiyum",
      "atomicMass": "114.818(3)",
      "electronicConfiguration": "[Kr] 4d10 5s2 5p1",
      "electronegativity": 1.78,
      "atomicRadius": 144,
      "ionRadius": "80 (+3)",
      "vanDerWaalsRadius": 193,
      "ionizationEnergy": 558,
      "electronAffinity": -29,
      "oxidationStates": "1, 2, 3",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 430,
      "boilingPoint": 2345,
      "density": 7.31,
      "groupBlock": "metal",
      "yearDiscovered": 1863,
      "block": "p",
      "period": 5,
      "group": 13
    },
    {
      "atomicNumber": 50,
      "symbol": "Sn",
      "name": "Kalay",
      "atomicMass": "118.710(7)",
      "electronicConfiguration": "[Kr] 4d10 5s2 5p2",
      "electronegativity": 1.96,
      "atomicRadius": 141,
      "ionRadius": "112 (+2)",
      "vanDerWaalsRadius": 217,
      "ionizationEnergy": 709,
      "electronAffinity": -107,
      "oxidationStates": "-4, 2, 4",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 505,
      "boilingPoint": 2875,
      "density": 7.31,
      "groupBlock": "metal",
      "yearDiscovered": "Antik",
      "block": "p",
      "period": 5,
      "group": 14
    },
    {
      "atomicNumber": 51,
      "symbol": "Sb",
      "name": "Antimon",
      "atomicMass": "121.760(1)",
      "electronicConfiguration": "[Kr] 4d10 5s2 5p3",
      "electronegativity": 2.05,
      "atomicRadius": 138,
      "ionRadius": "76 (+3)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 834,
      "electronAffinity": -103,
      "oxidationStates": "-3, 3, 5",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 904,
      "boilingPoint": 1860,
      "density": 6.697,
      "groupBlock": "yarı metal",
      "yearDiscovered": "Antik",
      "block": "p",
      "period": 5,
      "group": 15
    },
    {
      "atomicNumber": 52,
      "symbol": "Te",
      "name": "Tellür",
      "atomicMass": "127.60(3)",
      "electronicConfiguration": "[Kr] 4d10 5s2 5p4",
      "electronegativity": 2.1,
      "atomicRadius": 135,
      "ionRadius": "221 (-2)",
      "vanDerWaalsRadius": 206,
      "ionizationEnergy": 869,
      "electronAffinity": -190,
      "oxidationStates": "-2, 2, 4, 5, 6",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 723,
      "boilingPoint": 1261,
      "density": 6.24,
      "groupBlock": "yarı metal",
      "yearDiscovered": 1782,
      "block": "p",
      "period": 5,
      "group": 16
    },
    {
      "atomicNumber": 53,
      "symbol": "I",
      "name": "İyot",
      "atomicMass": "126.90447(3)",
      "electronicConfiguration": "[Kr] 4d10 5s2 5p5",
      "electronegativity": 2.66,
      "atomicRadius": 133,
      "ionRadius": "220 (-1)",
      "vanDerWaalsRadius": 198,
      "ionizationEnergy": 1008,
      "electronAffinity": -295,
      "oxidationStates": "-1, 1, 3, 5, 7",
      "standardState": "Katı",
      "bondingType": "Kovalent Bağ",
      "meltingPoint": 387,
      "boilingPoint": 457,
      "density": 4.94,
      "groupBlock": "halojen",
      "yearDiscovered": 1811,
      "block": "p",
      "period": 5,
      "group": 17
    },
    {
      "atomicNumber": 54,
      "symbol": "Xe",
      "name": "Ksenon",
      "atomicMass": "131.293(6)",
      "electronicConfiguration": "[Kr] 4d10 5s2 5p6",
      "electronegativity": "bilinmiyor",
      "atomicRadius": 130,
      "ionRadius": "48 (+8)",
      "vanDerWaalsRadius": 216,
      "ionizationEnergy": 1170,
      "electronAffinity": 0,
      "oxidationStates": "2, 4, 6, 8",
      "standardState": "Gaz",
      "bondingType": "atomik",
      "meltingPoint": 161,
      "boilingPoint": 165,
      "density": 0.0059,
      "groupBlock": "soy gaz",
      "yearDiscovered": 1898,
      "block": "p",
      "period": 5,
      "group": 18
    },
    {
      "atomicNumber": 55,
      "symbol": "Cs",
      "name": "Sezyum",
      "atomicMass": "132.9054519(2)",
      "electronicConfiguration": "[Xe] 6s1",
      "electronegativity": 0.79,
      "atomicRadius": 225,
      "ionRadius": "167 (+1)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 376,
      "electronAffinity": -46,
      "oxidationStates": 1,
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 302,
      "boilingPoint": 944,
      "density": 1.879,
      "groupBlock": "alkali metal",
      "yearDiscovered": 1860,
      "block": "s",
      "period": 6,
      "group": 1
    },
    {
      "atomicNumber": 56,
      "symbol": "Ba",
      "name": "Baryum",
      "atomicMass": "137.327(7)",
      "electronicConfiguration": "[Xe] 6s2",
      "electronegativity": 0.89,
      "atomicRadius": 198,
      "ionRadius": "135 (+2)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 503,
      "electronAffinity": -14,
      "oxidationStates": 2,
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1000,
      "boilingPoint": 2143,
      "density": 3.51,
      "groupBlock": "alkali toprak metal",
      "yearDiscovered": 1808,
      "block": "s",
      "period": 6,
      "group": 2
    },
    {
      "atomicNumber": 57,
      "symbol": "La",
      "name": "Lantan",
      "atomicMass": "138.90547(7)",
      "electronicConfiguration": "[Xe] 5d1 6s2",
      "electronegativity": 1.1,
      "atomicRadius": 169,
      "ionRadius": "103.2 (+3)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 538,
      "electronAffinity": -48,
      "oxidationStates": "2, 3",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1193,
      "boilingPoint": 3737,
      "density": 6.146,
      "groupBlock": "lantanit",
      "yearDiscovered": 1839,
      "block": "f",
      "period": 6,
      "group": 3
    },
    {
      "atomicNumber": 58,
      "symbol": "Ce",
      "name": "Seryum",
      "atomicMass": "140.116(1)",
      "electronicConfiguration": "[Xe] 4f1 5d1 6s2",
      "electronegativity": 1.12,
      "atomicRadius": "bilinmiyor",
      "ionRadius": "102 (+3)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 534,
      "electronAffinity": -50,
      "oxidationStates": "2, 3, 4",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1071,
      "boilingPoint": 3633,
      "density": 6.689,
      "groupBlock": "lantanit",
      "yearDiscovered": 1803,
      "block": "f",
      "period": 6,
      "group": 3
    },
    {
      "atomicNumber": 59,
      "symbol": "Pr",
      "name": "Praseodim",
      "atomicMass": "140.90765(2)",
      "electronicConfiguration": "[Xe] 4f3 6s2",
      "electronegativity": 1.13,
      "atomicRadius": "bilinmiyor",
      "ionRadius": "99 (+3)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 527,
      "electronAffinity": -50,
      "oxidationStates": "2, 3, 4",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1204,
      "boilingPoint": 3563,
      "density": 6.64,
      "groupBlock": "lantanit",
      "yearDiscovered": 1885,
      "block": "f",
      "period": 6,
      "group": 3
    },
    {
      "atomicNumber": 60,
      "symbol": "Nd",
      "name": "Neodimyum",
      "atomicMass": "144.242(3)",
      "electronicConfiguration": "[Xe] 4f4 6s2",
      "electronegativity": 1.14,
      "atomicRadius": "bilinmiyor",
      "ionRadius": "129 (+2)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 533,
      "electronAffinity": -50,
      "oxidationStates": "2, 3",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1294,
      "boilingPoint": 3373,
      "density": 7.01,
      "groupBlock": "lantanit",
      "yearDiscovered": 1885,
      "block": "f",
      "period": 6,
      "group": 3
    },
    {
      "atomicNumber": 61,
      "symbol": "Pm",
      "name": "Prometyum",
      "atomicMass": [
        145
      ],
      "electronicConfiguration": "[Xe] 4f5 6s2",
      "electronegativity": 1.13,
      "atomicRadius": "bilinmiyor",
      "ionRadius": "97 (+3)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 540,
      "electronAffinity": -50,
      "oxidationStates": 3,
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1373,
      "boilingPoint": 3273,
      "density": 7.264,
      "groupBlock": "lantanit",
      "yearDiscovered": 1947,
      "block": "f",
      "period": 6,
      "group": 3
    },
    {
      "atomicNumber": 62,
      "symbol": "Sm",
      "name": "Samaryum",
      "atomicMass": "150.36(2)",
      "electronicConfiguration": "[Xe] 4f6 6s2",
      "electronegativity": 1.17,
      "atomicRadius": "bilinmiyor",
      "ionRadius": "122 (+2)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 545,
      "electronAffinity": -50,
      "oxidationStates": "2, 3",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1345,
      "boilingPoint": 2076,
      "density": 7.353,
      "groupBlock": "lantanit",
      "yearDiscovered": 1853,
      "block": "f",
      "period": 6,
      "group": 3
    },
    {
      "atomicNumber": 63,
      "symbol": "Eu",
      "name": "Evropiyum",
      "atomicMass": "151.964(1)",
      "electronicConfiguration": "[Xe] 4f7 6s2",
      "electronegativity": 1.2,
      "atomicRadius": "bilinmiyor",
      "ionRadius": "117 (+2)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 547,
      "electronAffinity": -50,
      "oxidationStates": "2, 3",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1095,
      "boilingPoint": 1800,
      "density": 5.244,
      "groupBlock": "lantanit",
      "yearDiscovered": 1901,
      "block": "f",
      "period": 6,
      "group": 3
    },
    {
      "atomicNumber": 64,
      "symbol": "Gd",
      "name": "Gadolinyum",
      "atomicMass": "157.25(3)",
      "electronicConfiguration": "[Xe] 4f7 5d1 6s2",
      "electronegativity": 1.2,
      "atomicRadius": "bilinmiyor",
      "ionRadius": "93.8 (+3)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 593,
      "electronAffinity": -50,
      "oxidationStates": "1, 2, 3",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1586,
      "boilingPoint": 3523,
      "density": 7.901,
      "groupBlock": "lantanit",
      "yearDiscovered": 1880,
      "block": "f",
      "period": 6,
      "group": 3
    },
    {
      "atomicNumber": 65,
      "symbol": "Tb",
      "name": "Terbiyum",
      "atomicMass": "158.92535(2)",
      "electronicConfiguration": "[Xe] 4f9 6s2",
      "electronegativity": 1.2,
      "atomicRadius": "bilinmiyor",
      "ionRadius": "92.3 (+3)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 566,
      "electronAffinity": -50,
      "oxidationStates": "1, 3, 4",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1629,
      "boilingPoint": 3503,
      "density": 8.219,
      "groupBlock": "lantanit",
      "yearDiscovered": 1843,
      "block": "f",
      "period": 6,
      "group": 3
    },
    {
      "atomicNumber": 66,
      "symbol": "Dy",
      "name": "Disprozyum",
      "atomicMass": "162.500(1)",
      "electronicConfiguration": "[Xe] 4f10 6s2",
      "electronegativity": 1.22,
      "atomicRadius": "bilinmiyor",
      "ionRadius": "107 (+2)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 573,
      "electronAffinity": -50,
      "oxidationStates": "2, 3",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1685,
      "boilingPoint": 2840,
      "density": 8.551,
      "groupBlock": "lantanit",
      "yearDiscovered": 1886,
      "block": "f",
      "period": 6,
      "group": 3
    },
    {
      "atomicNumber": 67,
      "symbol": "Ho",
      "name": "Holmiyum",
      "atomicMass": "164.93032(2)",
      "electronicConfiguration": "[Xe] 4f11 6s2",
      "electronegativity": 1.23,
      "atomicRadius": "bilinmiyor",
      "ionRadius": "90.1 (+3)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 581,
      "electronAffinity": -50,
      "oxidationStates": 3,
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1747,
      "boilingPoint": 2973,
      "density": 8.795,
      "groupBlock": "lantanit",
      "yearDiscovered": 1878,
      "block": "f",
      "period": 6,
      "group": 3
    },
    {
      "atomicNumber": 68,
      "symbol": "Er",
      "name": "Erbiyum",
      "atomicMass": "167.259(3)",
      "electronicConfiguration": "[Xe] 4f12 6s2",
      "electronegativity": 1.24,
      "atomicRadius": "bilinmiyor",
      "ionRadius": "89 (+3)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 589,
      "electronAffinity": -50,
      "oxidationStates": 3,
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1770,
      "boilingPoint": 3141,
      "density": 9.066,
      "groupBlock": "lantanit",
      "yearDiscovered": 1842,
      "block": "f",
      "period": 6,
      "group": 3
    },
    {
      "atomicNumber": 69,
      "symbol": "Tm",
      "name": "Tulyum",
      "atomicMass": "168.93421(2)",
      "electronicConfiguration": "[Xe] 4f13 6s2",
      "electronegativity": 1.25,
      "atomicRadius": "bilinmiyor",
      "ionRadius": "103 (+2)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 597,
      "electronAffinity": -50,
      "oxidationStates": "2, 3",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1818,
      "boilingPoint": 2223,
      "density": 9.321,
      "groupBlock": "lantanit",
      "yearDiscovered": 1879,
      "block": "f",
      "period": 6,
      "group": 3
    },
    {
      "atomicNumber": 70,
      "symbol": "Yb",
      "name": "İterbiyum",
      "atomicMass": "173.054(5)",
      "electronicConfiguration": "[Xe] 4f14 6s2",
      "electronegativity": 1.1,
      "atomicRadius": "bilinmiyor",
      "ionRadius": "102 (+2)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 603,
      "electronAffinity": -50,
      "oxidationStates": "2, 3",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1092,
      "boilingPoint": 1469,
      "density": 6.57,
      "groupBlock": "lantanit",
      "yearDiscovered": 1878,
      "block": "f",
      "period": 6,
      "group": 3
    },
    {
      "atomicNumber": 71,
      "symbol": "Lu",
      "name": "Lutesyum",
      "atomicMass": "174.9668(1)",
      "electronicConfiguration": "[Xe] 4f14 5d1 6s2",
      "electronegativity": 1.27,
      "atomicRadius": 160,
      "ionRadius": "86.1 (+3)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 524,
      "electronAffinity": -50,
      "oxidationStates": 3,
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1936,
      "boilingPoint": 3675,
      "density": 9.841,
      "groupBlock": "lantanit",
      "yearDiscovered": 1907,
      "block": "d",
      "period": 6,
      "group": 3
    },
    {
      "atomicNumber": 72,
      "symbol": "Hf",
      "name": "Hafniyum",
      "atomicMass": "178.49(2)",
      "electronicConfiguration": "[Xe] 4f14 5d2 6s2",
      "electronegativity": 1.3,
      "atomicRadius": 150,
      "ionRadius": "71 (+4)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 659,
      "electronAffinity": 0,
      "oxidationStates": "2, 3, 4",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 2506,
      "boilingPoint": 4876,
      "density": 13.31,
      "groupBlock": "geçiş metali",
      "yearDiscovered": 1923,
      "block": "d",
      "period": 6,
      "group": 4
    },
    {
      "atomicNumber": 73,
      "symbol": "Ta",
      "name": "Tantal",
      "atomicMass": "180.94788(2)",
      "electronicConfiguration": "[Xe] 4f14 5d3 6s2",
      "electronegativity": 1.5,
      "atomicRadius": 138,
      "ionRadius": "72 (+3)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 761,
      "electronAffinity": -31,
      "oxidationStates": "-1, 2, 3, 4, 5",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 3290,
      "boilingPoint": 5731,
      "density": 16.65,
      "groupBlock": "geçiş metali",
      "yearDiscovered": 1802,
      "block": "d",
      "period": 6,
      "group": 5
    },
    {
      "atomicNumber": 74,
      "symbol": "W",
      "name": "Tungsten",
      "atomicMass": "183.84(1)",
      "electronicConfiguration": "[Xe] 4f14 5d4 6s2",
      "electronegativity": 2.36,
      "atomicRadius": 146,
      "ionRadius": "66 (+4)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 770,
      "electronAffinity": -79,
      "oxidationStates": "-2, -1, 1, 2, 3, 4, 5, 6",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 3695,
      "boilingPoint": 5828,
      "density": 19.25,
      "groupBlock": "geçiş metali",
      "yearDiscovered": 1783,
      "block": "d",
      "period": 6,
      "group": 6
    },
    {
      "atomicNumber": 75,
      "symbol": "Re",
      "name": "Renyum",
      "atomicMass": "186.207(1)",
      "electronicConfiguration": "[Xe] 4f14 5d5 6s2",
      "electronegativity": 1.9,
      "atomicRadius": 159,
      "ionRadius": "63 (+4)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 760,
      "electronAffinity": -15,
      "oxidationStates": "-3, -1, 1, 2, 3, 4, 5, 6, 7",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 3459,
      "boilingPoint": 5869,
      "density": 21.02,
      "groupBlock": "geçiş metali",
      "yearDiscovered": 1925,
      "block": "d",
      "period": 6,
      "group": 7
    },
    {
      "atomicNumber": 76,
      "symbol": "Os",
      "name": "Osmiyum",
      "atomicMass": "190.23(3)",
      "electronicConfiguration": "[Xe] 4f14 5d6 6s2",
      "electronegativity": 2.2,
      "atomicRadius": 128,
      "ionRadius": "63 (+4)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 840,
      "electronAffinity": -106,
      "oxidationStates": "-2, -1, 1, 2, 3, 4, 5, 6, 7, 8",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 3306,
      "boilingPoint": 5285,
      "density": 22.61,
      "groupBlock": "geçiş metali",
      "yearDiscovered": 1803,
      "block": "d",
      "period": 6,
      "group": 8
    },
    {
      "atomicNumber": 77,
      "symbol": "Ir",
      "name": "İridyum",
      "atomicMass": "192.217(3)",
      "electronicConfiguration": "[Xe] 4f14 5d7 6s2",
      "electronegativity": 2.2,
      "atomicRadius": 137,
      "ionRadius": "68 (+3)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 880,
      "electronAffinity": -151,
      "oxidationStates": "-3, -1, 1, 2, 3, 4, 5, 6",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 2739,
      "boilingPoint": 4701,
      "density": 22.65,
      "groupBlock": "geçiş metali",
      "yearDiscovered": 1803,
      "block": "d",
      "period": 6,
      "group": 9
    },
    {
      "atomicNumber": 78,
      "symbol": "Pt",
      "name": "Platin",
      "atomicMass": "195.084(9)",
      "electronicConfiguration": "[Xe] 4f14 5d9 6s1",
      "electronegativity": 2.28,
      "atomicRadius": 128,
      "ionRadius": "86 (+2)",
      "vanDerWaalsRadius": 175,
      "ionizationEnergy": 870,
      "electronAffinity": -205,
      "oxidationStates": "2, 4, 5, 6",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 2041,
      "boilingPoint": 4098,
      "density": 21.09,
      "groupBlock": "geçiş metali",
      "yearDiscovered": "Antik",
      "block": "d",
      "period": 6,
      "group": 10
    },
    {
      "atomicNumber": 79,
      "symbol": "Au",
      "name": "Altın",
      "atomicMass": "196.966569(4)",
      "electronicConfiguration": "[Xe] 4f14 5d10 6s1",
      "electronegativity": 2.54,
      "atomicRadius": 144,
      "ionRadius": "137 (+1)",
      "vanDerWaalsRadius": 166,
      "ionizationEnergy": 890,
      "electronAffinity": -223,
      "oxidationStates": "-1, 1, 2, 3, 5",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1337,
      "boilingPoint": 3129,
      "density": 19.3,
      "groupBlock": "geçiş metali",
      "yearDiscovered": "Antik",
      "block": "d",
      "period": 6,
      "group": 11
    },
    {
      "atomicNumber": 80,
      "symbol": "Hg",
      "name": "Civa",
      "atomicMass": "200.59(2)",
      "electronicConfiguration": "[Xe] 4f14 5d10 6s2",
      "electronegativity": 2,
      "atomicRadius": 149,
      "ionRadius": "119 (+1)",
      "vanDerWaalsRadius": 155,
      "ionizationEnergy": 1007,
      "electronAffinity": 0,
      "oxidationStates": "1, 2, 4",
      "standardState": "sıvı",
      "bondingType": "Metalik",
      "meltingPoint": 234,
      "boilingPoint": 630,
      "density": 13.534,
      "groupBlock": "geçiş metali",
      "yearDiscovered": "Antik",
      "block": "d",
      "period": 6,
      "group": 12
    },
    {
      "atomicNumber": 81,
      "symbol": "Tl",
      "name": "Talyum",
      "atomicMass": "204.3833(2)",
      "electronicConfiguration": "[Xe] 4f14 5d10 6s2 6p1",
      "electronegativity": 2.04,
      "atomicRadius": 148,
      "ionRadius": "150 (+1)",
      "vanDerWaalsRadius": 196,
      "ionizationEnergy": 589,
      "electronAffinity": -19,
      "oxidationStates": "1, 3",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 577,
      "boilingPoint": 1746,
      "density": 11.85,
      "groupBlock": "metal",
      "yearDiscovered": 1861,
      "block": "p",
      "period": 6,
      "group": 13
    },
    {
      "atomicNumber": 82,
      "symbol": "Pb",
      "name": "Kurşun",
      "atomicMass": "207.2(1)",
      "electronicConfiguration": "[Xe] 4f14 5d10 6s2 6p2",
      "electronegativity": 2.33,
      "atomicRadius": 147,
      "ionRadius": "119 (+2)",
      "vanDerWaalsRadius": 202,
      "ionizationEnergy": 716,
      "electronAffinity": -35,
      "oxidationStates": "-4, 2, 4",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 601,
      "boilingPoint": 2022,
      "density": 11.34,
      "groupBlock": "metal",
      "yearDiscovered": "Antik",
      "block": "p",
      "period": 6,
      "group": 14
    },
    {
      "atomicNumber": 83,
      "symbol": "Bi",
      "name": "Bizmut",
      "atomicMass": "208.98040(1)",
      "electronicConfiguration": "[Xe] 4f14 5d10 6s2 6p3",
      "electronegativity": 2.02,
      "atomicRadius": 146,
      "ionRadius": "103 (+3)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 703,
      "electronAffinity": -91,
      "oxidationStates": "-3, 3, 5",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 544,
      "boilingPoint": 1837,
      "density": 9.78,
      "groupBlock": "metal",
      "yearDiscovered": "Antik",
      "block": "p",
      "period": 6,
      "group": 15
    },
    {
      "atomicNumber": 84,
      "symbol": "Po",
      "name": "Polonyum",
      "atomicMass": [
        209
      ],
      "electronicConfiguration": "[Xe] 4f14 5d10 6s2 6p4",
      "electronegativity": 2,
      "atomicRadius": "bilinmiyor",
      "ionRadius": "94 (+4)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 812,
      "electronAffinity": -183,
      "oxidationStates": "-2, 2, 4, 6",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 527,
      "boilingPoint": 1235,
      "density": 9.196,
      "groupBlock": "yarı metal",
      "yearDiscovered": 1898,
      "block": "p",
      "period": 6,
      "group": 16
    },
    {
      "atomicNumber": 85,
      "symbol": "At",
      "name": "Astatin",
      "atomicMass": [
        210
      ],
      "electronicConfiguration": "[Xe] 4f14 5d10 6s2 6p5",
      "electronegativity": 2.2,
      "atomicRadius": "bilinmiyor",
      "ionRadius": "62 (+7)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 920,
      "electronAffinity": -270,
      "oxidationStates": "-1, 1, 3, 5",
      "standardState": "Katı",
      "bondingType": "Kovalent Bağ",
      "meltingPoint": 575,
      "boilingPoint": "bilinmiyor",
      "density": "bilinmiyor",
      "groupBlock": "halojen",
      "yearDiscovered": 1940,
      "block": "p",
      "period": 6,
      "group": 17
    },
    {
      "atomicNumber": 86,
      "symbol": "Rn",
      "name": "Radon",
      "atomicMass": [
        222
      ],
      "electronicConfiguration": "[Xe] 4f14 5d10 6s2 6p6",
      "electronegativity": "bilinmiyor",
      "atomicRadius": 145,
      "ionRadius": "bilinmiyor",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 1037,
      "electronAffinity": "bilinmiyor",
      "oxidationStates": 2,
      "standardState": "Gaz",
      "bondingType": "atomik",
      "meltingPoint": 202,
      "boilingPoint": 211,
      "density": 0.00973,
      "groupBlock": "soy gaz",
      "yearDiscovered": 1900,
      "block": "p",
      "period": 6,
      "group": 18
    },
    {
      "atomicNumber": 87,
      "symbol": "Fr",
      "name": "Fransiyum",
      "atomicMass": [
        223
      ],
      "electronicConfiguration": "[Rn] 7s1",
      "electronegativity": 0.7,
      "atomicRadius": "bilinmiyor",
      "ionRadius": "180 (+1)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 380,
      "electronAffinity": "bilinmiyor",
      "oxidationStates": 1,
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": "bilinmiyor",
      "boilingPoint": "bilinmiyor",
      "density": "bilinmiyor",
      "groupBlock": "alkali metal",
      "yearDiscovered": 1939,
      "block": "s",
      "period": 7,
      "group": 1
    },
    {
      "atomicNumber": 88,
      "symbol": "Ra",
      "name": "Radyum",
      "atomicMass": [
        226
      ],
      "electronicConfiguration": "[Rn] 7s2",
      "electronegativity": 0.9,
      "atomicRadius": "bilinmiyor",
      "ionRadius": "148 (+2)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 509,
      "electronAffinity": "bilinmiyor",
      "oxidationStates": 2,
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 973,
      "boilingPoint": 2010,
      "density": 5,
      "groupBlock": "alkali toprak metal",
      "yearDiscovered": 1898,
      "block": "s",
      "period": 7,
      "group": 2
    },
    {
      "atomicNumber": 89,
      "symbol": "Ac",
      "name": "Aktinyum",
      "atomicMass": [
        227
      ],
      "electronicConfiguration": "[Rn] 6d1 7s2",
      "electronegativity": 1.1,
      "atomicRadius": "bilinmiyor",
      "ionRadius": "112 (+3)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 499,
      "electronAffinity": "bilinmiyor",
      "oxidationStates": 3,
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1323,
      "boilingPoint": 3473,
      "density": 10.07,
      "groupBlock": "aktinit",
      "yearDiscovered": 1899,
      "block": "f",
      "period": 7,
      "group": 3
    },
    {
      "atomicNumber": 90,
      "symbol": "Th",
      "name": "Toryum",
      "atomicMass": "232.03806(2)",
      "electronicConfiguration": "[Rn] 6d2 7s2",
      "electronegativity": 1.3,
      "atomicRadius": "bilinmiyor",
      "ionRadius": "94 (+4)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 587,
      "electronAffinity": "bilinmiyor",
      "oxidationStates": "2, 3, 4",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 2023,
      "boilingPoint": 5093,
      "density": 11.724,
      "groupBlock": "aktinit",
      "yearDiscovered": 1828,
      "block": "f",
      "period": 7,
      "group": 3
    },
    {
      "atomicNumber": 91,
      "symbol": "Pa",
      "name": "Protaktiryum",
      "atomicMass": "231.03588(2)",
      "electronicConfiguration": "[Rn] 5f2 6d1 7s2",
      "electronegativity": 1.5,
      "atomicRadius": "bilinmiyor",
      "ionRadius": "104 (+3)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 568,
      "electronAffinity": "bilinmiyor",
      "oxidationStates": "3, 4, 5",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1845,
      "boilingPoint": 4273,
      "density": 15.37,
      "groupBlock": "aktinit",
      "yearDiscovered": 1913,
      "block": "f",
      "period": 7,
      "group": 3
    },
    {
      "atomicNumber": 92,
      "symbol": "U",
      "name": "Uranyum",
      "atomicMass": "238.02891(3)",
      "electronicConfiguration": "[Rn] 5f3 6d1 7s2",
      "electronegativity": 1.38,
      "atomicRadius": "bilinmiyor",
      "ionRadius": "102.5 (+3)",
      "vanDerWaalsRadius": 186,
      "ionizationEnergy": 598,
      "electronAffinity": "bilinmiyor",
      "oxidationStates": "3, 4, 5, 6",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1408,
      "boilingPoint": 4200,
      "density": 19.05,
      "groupBlock": "aktinit",
      "yearDiscovered": 1789,
      "block": "f",
      "period": 7,
      "group": 3
    },
    {
      "atomicNumber": 93,
      "symbol": "Np",
      "name": "Neptünyum",
      "atomicMass": [
        237
      ],
      "electronicConfiguration": "[Rn] 5f4 6d1 7s2",
      "electronegativity": 1.36,
      "atomicRadius": "bilinmiyor",
      "ionRadius": "110 (+2)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 605,
      "electronAffinity": "bilinmiyor",
      "oxidationStates": "3, 4, 5, 6, 7",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 917,
      "boilingPoint": 4273,
      "density": 20.45,
      "groupBlock": "aktinit",
      "yearDiscovered": 1940,
      "block": "f",
      "period": 7,
      "group": 3
    },
    {
      "atomicNumber": 94,
      "symbol": "Pu",
      "name": "Plütonyum",
      "atomicMass": [
        244
      ],
      "electronicConfiguration": "[Rn] 5f6 7s2",
      "electronegativity": 1.28,
      "atomicRadius": "bilinmiyor",
      "ionRadius": "100 (+3)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 585,
      "electronAffinity": "bilinmiyor",
      "oxidationStates": "3, 4, 5, 6, 7",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 913,
      "boilingPoint": 3503,
      "density": 19.816,
      "groupBlock": "aktinit",
      "yearDiscovered": 1940,
      "block": "f",
      "period": 7,
      "group": 3
    },
    {
      "atomicNumber": 95,
      "symbol": "Am",
      "name": "Amerikyum",
      "atomicMass": [
        243
      ],
      "electronicConfiguration": "[Rn] 5f7 7s2",
      "electronegativity": 1.3,
      "atomicRadius": "bilinmiyor",
      "ionRadius": "126 (+2)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 578,
      "electronAffinity": "bilinmiyor",
      "oxidationStates": "2, 3, 4, 5, 6",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1449,
      "boilingPoint": 2284,
      "density": "bilinmiyor",
      "groupBlock": "aktinit",
      "yearDiscovered": 1944,
      "block": "f",
      "period": 7,
      "group": 3
    },
    {
      "atomicNumber": 96,
      "symbol": "Cm",
      "name": "Küriyum",
      "atomicMass": [
        247
      ],
      "electronicConfiguration": "[Rn] 5f7 6d1 7s2",
      "electronegativity": 1.3,
      "atomicRadius": "bilinmiyor",
      "ionRadius": "97 (+3)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 581,
      "electronAffinity": "bilinmiyor",
      "oxidationStates": "3, 4",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1618,
      "boilingPoint": 3383,
      "density": 13.51,
      "groupBlock": "aktinit",
      "yearDiscovered": 1944,
      "block": "f",
      "period": 7,
      "group": 3
    },
    {
      "atomicNumber": 97,
      "symbol": "Bk",
      "name": "Berkelyum",
      "atomicMass": [
        247
      ],
      "electronicConfiguration": "[Rn] 5f9 7s2",
      "electronegativity": 1.3,
      "atomicRadius": "bilinmiyor",
      "ionRadius": "96 (+3)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 601,
      "electronAffinity": "bilinmiyor",
      "oxidationStates": "3, 4",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1323,
      "boilingPoint": "bilinmiyor",
      "density": 14.78,
      "groupBlock": "aktinit",
      "yearDiscovered": 1949,
      "block": "f",
      "period": 7,
      "group": 3
    },
    {
      "atomicNumber": 98,
      "symbol": "Cf",
      "name": "Kaliforniyum",
      "atomicMass": [
        251
      ],
      "electronicConfiguration": "[Rn] 5f10 7s2",
      "electronegativity": 1.3,
      "atomicRadius": "bilinmiyor",
      "ionRadius": "95 (+3)",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 608,
      "electronAffinity": "bilinmiyor",
      "oxidationStates": "2, 3, 4",
      "standardState": "Katı",
      "bondingType": "Metalik",
      "meltingPoint": 1173,
      "boilingPoint": "bilinmiyor",
      "density": 15.1,
      "groupBlock": "aktinit",
      "yearDiscovered": 1950,
      "block": "f",
      "period": 7,
      "group": 3
    },
    {
      "atomicNumber": 99,
      "symbol": "Es",
      "name": "Einsteinyum",
      "atomicMass": [
        252
      ],
      "electronicConfiguration": "[Rn] 5f11 7s2",
      "electronegativity": 1.3,
      "atomicRadius": "bilinmiyor",
      "ionRadius": "bilinmiyor",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 619,
      "electronAffinity": "bilinmiyor",
      "oxidationStates": "2, 3",
      "standardState": "Katı",
      "bondingType": "bilinmiyor",
      "meltingPoint": 1133,
      "boilingPoint": "bilinmiyor",
      "density": "bilinmiyor",
      "groupBlock": "aktinit",
      "yearDiscovered": 1952,
      "block": "f",
      "period": 7,
      "group": 3
    },
    {
      "atomicNumber": 100,
      "symbol": "Fm",
      "name": "Fermiyum",
      "atomicMass": [
        257
      ],
      "electronicConfiguration": "[Rn] 5f12 7s2",
      "electronegativity": 1.3,
      "atomicRadius": "bilinmiyor",
      "ionRadius": "bilinmiyor",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 627,
      "electronAffinity": "bilinmiyor",
      "oxidationStates": "2, 3",
      "standardState": "bilinmiyor",
      "bondingType": "bilinmiyor",
      "meltingPoint": 1800,
      "boilingPoint": "bilinmiyor",
      "density": "bilinmiyor",
      "groupBlock": "aktinit",
      "yearDiscovered": 1952,
      "block": "f",
      "period": 7,
      "group": 3
    },
    {
      "atomicNumber": 101,
      "symbol": "Md",
      "name": "Mendelevyum",
      "atomicMass": [
        258
      ],
      "electronicConfiguration": "[Rn] 5f13 7s2",
      "electronegativity": 1.3,
      "atomicRadius": "bilinmiyor",
      "ionRadius": "bilinmiyor",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 635,
      "electronAffinity": "bilinmiyor",
      "oxidationStates": "2, 3",
      "standardState": "bilinmiyor",
      "bondingType": "bilinmiyor",
      "meltingPoint": 1100,
      "boilingPoint": "bilinmiyor",
      "density": "bilinmiyor",
      "groupBlock": "aktinit",
      "yearDiscovered": 1955,
      "block": "f",
      "period": 7,
      "group": 3
    },
    {
      "atomicNumber": 102,
      "symbol": "No",
      "name": "Nobelyum",
      "atomicMass": [
        259
      ],
      "electronicConfiguration": "[Rn] 5f14 7s2",
      "electronegativity": 1.3,
      "atomicRadius": "bilinmiyor",
      "ionRadius": "bilinmiyor",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": 642,
      "electronAffinity": "bilinmiyor",
      "oxidationStates": "2, 3",
      "standardState": "bilinmiyor",
      "bondingType": "bilinmiyor",
      "meltingPoint": 1100,
      "boilingPoint": "bilinmiyor",
      "density": "bilinmiyor",
      "groupBlock": "aktinit",
      "yearDiscovered": 1957,
      "block": "f",
      "period": 7,
      "group": 3
    },
    {
      "atomicNumber": 103,
      "symbol": "Lr",
      "name": "Lavrensiyum",
      "atomicMass": [
        262
      ],
      "electronicConfiguration": "[Rn] 5f14 7s2 7p1",
      "electronegativity": 1.3,
      "atomicRadius": "bilinmiyor",
      "ionRadius": "bilinmiyor",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": "bilinmiyor",
      "electronAffinity": "bilinmiyor",
      "oxidationStates": 3,
      "standardState": "bilinmiyor",
      "bondingType": "bilinmiyor",
      "meltingPoint": 1900,
      "boilingPoint": "bilinmiyor",
      "density": "bilinmiyor",
      "groupBlock": "aktinit",
      "yearDiscovered": 1961,
      "block": "d",
      "period": 7,
      "group": 3
    },
    {
      "atomicNumber": 104,
      "symbol": "Rf",
      "name": "Rutherfordyum",
      "atomicMass": [
        267
      ],
      "electronicConfiguration": "[Rn] 5f14 6d2 7s2",
      "electronegativity": "bilinmiyor",
      "atomicRadius": "bilinmiyor",
      "ionRadius": "bilinmiyor",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": "bilinmiyor",
      "electronAffinity": "bilinmiyor",
      "oxidationStates": 4,
      "standardState": "bilinmiyor",
      "bondingType": "bilinmiyor",
      "meltingPoint": "bilinmiyor",
      "boilingPoint": "bilinmiyor",
      "density": "bilinmiyor",
      "groupBlock": "geçiş metali",
      "yearDiscovered": 1969,
      "block": "d",
      "period": 7,
      "group": 4
    },
    {
      "atomicNumber": 105,
      "symbol": "Db",
      "name": "Dubniyum",
      "atomicMass": [
        268
      ],
      "electronicConfiguration": "[Rn] 5f14 6d3 7s2",
      "electronegativity": "bilinmiyor",
      "atomicRadius": "bilinmiyor",
      "ionRadius": "bilinmiyor",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": "bilinmiyor",
      "electronAffinity": "bilinmiyor",
      "oxidationStates": "bilinmiyor",
      "standardState": "bilinmiyor",
      "bondingType": "bilinmiyor",
      "meltingPoint": "bilinmiyor",
      "boilingPoint": "bilinmiyor",
      "density": "bilinmiyor",
      "groupBlock": "geçiş metali",
      "yearDiscovered": 1967,
      "block": "d",
      "period": 7,
      "group": 5
    },
    {
      "atomicNumber": 106,
      "symbol": "Sg",
      "name": "Seaborgiyum",
      "atomicMass": [
        271
      ],
      "electronicConfiguration": "[Rn] 5f14 6d4 7s2",
      "electronegativity": "bilinmiyor",
      "atomicRadius": "bilinmiyor",
      "ionRadius": "bilinmiyor",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": "bilinmiyor",
      "electronAffinity": "bilinmiyor",
      "oxidationStates": "bilinmiyor",
      "standardState": "bilinmiyor",
      "bondingType": "bilinmiyor",
      "meltingPoint": "bilinmiyor",
      "boilingPoint": "bilinmiyor",
      "density": "bilinmiyor",
      "groupBlock": "geçiş metali",
      "yearDiscovered": 1974,
      "block": "d",
      "period": 7,
      "group": 6
    },
    {
      "atomicNumber": 107,
      "symbol": "Bh",
      "name": "Bohriyum",
      "atomicMass": [
        272
      ],
      "electronicConfiguration": "[Rn] 5f14 6d5 7s2",
      "electronegativity": "bilinmiyor",
      "atomicRadius": "bilinmiyor",
      "ionRadius": "bilinmiyor",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": "bilinmiyor",
      "electronAffinity": "bilinmiyor",
      "oxidationStates": "bilinmiyor",
      "standardState": "bilinmiyor",
      "bondingType": "bilinmiyor",
      "meltingPoint": "bilinmiyor",
      "boilingPoint": "bilinmiyor",
      "density": "bilinmiyor",
      "groupBlock": "geçiş metali",
      "yearDiscovered": 1976,
      "block": "d",
      "period": 7,
      "group": 7
    },
    {
      "atomicNumber": 108,
      "symbol": "Hs",
      "name": "Hassiyum",
      "atomicMass": [
        270
      ],
      "electronicConfiguration": "[Rn] 5f14 6d6 7s2",
      "electronegativity": "bilinmiyor",
      "atomicRadius": "bilinmiyor",
      "ionRadius": "bilinmiyor",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": "bilinmiyor",
      "electronAffinity": "bilinmiyor",
      "oxidationStates": "bilinmiyor",
      "standardState": "bilinmiyor",
      "bondingType": "bilinmiyor",
      "meltingPoint": "bilinmiyor",
      "boilingPoint": "bilinmiyor",
      "density": "bilinmiyor",
      "groupBlock": "geçiş metali",
      "yearDiscovered": 1984,
      "block": "d",
      "period": 7,
      "group": 8
    },
    {
      "atomicNumber": 109,
      "symbol": "Mt",
      "name": "Meitneriyum",
      "atomicMass": [
        276
      ],
      "electronicConfiguration": "[Rn] 5f14 6d7 7s2",
      "electronegativity": "bilinmiyor",
      "atomicRadius": "bilinmiyor",
      "ionRadius": "bilinmiyor",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": "bilinmiyor",
      "electronAffinity": "bilinmiyor",
      "oxidationStates": "bilinmiyor",
      "standardState": "bilinmiyor",
      "bondingType": "bilinmiyor",
      "meltingPoint": "bilinmiyor",
      "boilingPoint": "bilinmiyor",
      "density": "bilinmiyor",
      "groupBlock": "geçiş metali",
      "yearDiscovered": 1982,
      "block": "d",
      "period": 7,
      "group": 9
    },
    {
      "atomicNumber": 110,
      "symbol": "Ds",
      "name": "Darmstadtiyum",
      "atomicMass": [
        281
      ],
      "electronicConfiguration": "[Rn] 5f14 6d9 7s1",
      "electronegativity": "bilinmiyor",
      "atomicRadius": "bilinmiyor",
      "ionRadius": "bilinmiyor",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": "bilinmiyor",
      "electronAffinity": "bilinmiyor",
      "oxidationStates": "bilinmiyor",
      "standardState": "bilinmiyor",
      "bondingType": "bilinmiyor",
      "meltingPoint": "bilinmiyor",
      "boilingPoint": "bilinmiyor",
      "density": "bilinmiyor",
      "groupBlock": "geçiş metali",
      "yearDiscovered": 1994,
      "block": "d",
      "period": 7,
      "group": 10
    },
    {
      "atomicNumber": 111,
      "symbol": "Rg",
      "name": "Röntgenyum",
      "atomicMass": [
        280
      ],
      "electronicConfiguration": "[Rn] 5f14 6d10 7s1",
      "electronegativity": "bilinmiyor",
      "atomicRadius": "bilinmiyor",
      "ionRadius": "bilinmiyor",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": "bilinmiyor",
      "electronAffinity": "bilinmiyor",
      "oxidationStates": "bilinmiyor",
      "standardState": "bilinmiyor",
      "bondingType": "bilinmiyor",
      "meltingPoint": "bilinmiyor",
      "boilingPoint": "bilinmiyor",
      "density": "bilinmiyor",
      "groupBlock": "geçiş metali",
      "yearDiscovered": 1994,
      "block": "d",
      "period": 7,
      "group": 11
    },
    {
      "atomicNumber": 112,
      "symbol": "Cn",
      "name": "Kopermikyum",
      "atomicMass": [
        285
      ],
      "electronicConfiguration": "[Rn] 5f14 6d10 7s2",
      "electronegativity": "bilinmiyor",
      "atomicRadius": "bilinmiyor",
      "ionRadius": "bilinmiyor",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": "bilinmiyor",
      "electronAffinity": "bilinmiyor",
      "oxidationStates": "bilinmiyor",
      "standardState": "bilinmiyor",
      "bondingType": "bilinmiyor",
      "meltingPoint": "bilinmiyor",
      "boilingPoint": "bilinmiyor",
      "density": "bilinmiyor",
      "groupBlock": "geçiş metali",
      "yearDiscovered": 1996,
      "block": "d",
      "period": 7,
      "group": 12
    },
    {
      "atomicNumber": 113,
      "symbol": "Nh",
      "name": "Nihoniyum",
      "atomicMass": [
        284
      ],
      "electronicConfiguration": "[Rn] 5f14 6d10 7s2 7p1",
      "electronegativity": "bilinmiyor",
      "atomicRadius": "bilinmiyor",
      "ionRadius": "bilinmiyor",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": "bilinmiyor",
      "electronAffinity": "bilinmiyor",
      "oxidationStates": "bilinmiyor",
      "standardState": "bilinmiyor",
      "bondingType": "bilinmiyor",
      "meltingPoint": "bilinmiyor",
      "boilingPoint": "bilinmiyor",
      "density": "bilinmiyor",
      "groupBlock": "geçiş sonrası metal",
      "yearDiscovered": 2003,
      "block": "p",
      "period": 7,
      "group": 13
    },
    {
      "atomicNumber": 114,
      "symbol": "Fl",
      "name": "Flerovyum",
      "atomicMass": [
        289
      ],
      "electronicConfiguration": "[Rn] 5f14 6d10 7s2 7p2",
      "electronegativity": "bilinmiyor",
      "atomicRadius": "bilinmiyor",
      "ionRadius": "bilinmiyor",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": "bilinmiyor",
      "electronAffinity": "bilinmiyor",
      "oxidationStates": "bilinmiyor",
      "standardState": "bilinmiyor",
      "bondingType": "bilinmiyor",
      "meltingPoint": "bilinmiyor",
      "boilingPoint": "bilinmiyor",
      "density": "bilinmiyor",
      "groupBlock": "geçiş sonrası metal",
      "yearDiscovered": 1998,
      "block": "p",
      "period": 7,
      "group": 14
    },
    {
      "atomicNumber": 115,
      "symbol": "Mc",
      "name": "Moscoviyum",
      "atomicMass": [
        288
      ],
      "electronicConfiguration": "[Rn] 5f14 6d10 7s2 7p3",
      "electronegativity": "bilinmiyor",
      "atomicRadius": "bilinmiyor",
      "ionRadius": "bilinmiyor",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": "bilinmiyor",
      "electronAffinity": "bilinmiyor",
      "oxidationStates": "bilinmiyor",
      "standardState": "bilinmiyor",
      "bondingType": "bilinmiyor",
      "meltingPoint": "bilinmiyor",
      "boilingPoint": "bilinmiyor",
      "density": "bilinmiyor",
      "groupBlock": "geçiş sonrası metal",
      "yearDiscovered": 2003,
      "block": "p",
      "period": 7,
      "group": 15
    },
    {
      "atomicNumber": 116,
      "symbol": "Lv",
      "name": "Livermoryum",
      "atomicMass": [
        293
      ],
      "electronicConfiguration": "[Rn] 5f14 6d10 7s2 7p4",
      "electronegativity": "bilinmiyor",
      "atomicRadius": "bilinmiyor",
      "ionRadius": "bilinmiyor",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": "bilinmiyor",
      "electronAffinity": "bilinmiyor",
      "oxidationStates": "bilinmiyor",
      "standardState": "bilinmiyor",
      "bondingType": "bilinmiyor",
      "meltingPoint": "bilinmiyor",
      "boilingPoint": "bilinmiyor",
      "density": "bilinmiyor",
      "groupBlock": "geçiş sonrası metal",
      "yearDiscovered": 2000,
      "block": "p",
      "period": 7,
      "group": 16
    },
    {
      "atomicNumber": 117,
      "symbol": "Ts",
      "name": "Tennesin",
      "atomicMass": [
        294
      ],
      "electronicConfiguration": "[Rn] 5f14 6d10 7s2 7p5",
      "electronegativity": "bilinmiyor",
      "atomicRadius": "bilinmiyor",
      "ionRadius": "bilinmiyor",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": "bilinmiyor",
      "electronAffinity": "bilinmiyor",
      "oxidationStates": "bilinmiyor",
      "standardState": "bilinmiyor",
      "bondingType": "bilinmiyor",
      "meltingPoint": "bilinmiyor",
      "boilingPoint": "bilinmiyor",
      "density": "bilinmiyor",
      "groupBlock": "geçiş sonrası metal",
      "yearDiscovered": 2010,
      "block": "p",
      "period": 7,
      "group": 17
    },
    {
      "atomicNumber": 118,
      "symbol": "Og",
      "name": "Oganesson",
      "atomicMass": [
        294
      ],
      "electronicConfiguration": "[Rn] 5f14 6d10 7s2 7p6",
      "electronegativity": "bilinmiyor",
      "atomicRadius": "bilinmiyor",
      "ionRadius": "bilinmiyor",
      "vanDerWaalsRadius": "bilinmiyor",
      "ionizationEnergy": "bilinmiyor",
      "electronAffinity": "bilinmiyor",
      "oxidationStates": "bilinmiyor",
      "standardState": "bilinmiyor",
      "bondingType": "bilinmiyor",
      "meltingPoint": "bilinmiyor",
      "boilingPoint": "bilinmiyor",
      "density": "bilinmiyor",
      "groupBlock": "soy gaz",
      "yearDiscovered": 2002,
      "block": "p",
      "period": 7,
      "group": 18
    }
  ]